    /*
SELECT '

USE ['+name+']
GO
CREATE LOGIN [ANTT\claudio.ramos] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
CREATE USER [ANTT\claudio.ramos] FOR LOGIN [ANTT\claudio.ramos]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ANTT\claudio.ramos]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [ANTT\claudio.ramos]
GO
'
from sys.databases    */
	
	/*
		Dá permissão para todos os bancos para um usuário de desenvolvimento.
	
	*/
	
	USE [BD_APOIO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_ASCOM];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_AUTORIZACAO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_BARRAMENTO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_BMA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_CANAL_VERDE];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_COBRANCA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_COBRANCA_2];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_COMUM];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_CONTRATO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_CONTROLEACESSO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_CORP];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_CORPORATIVO_02];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_CORPORATIVO_03];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_CORPORATIVO_ANTT];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_CPA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_CSS];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_DESEMPENHO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_DOCFLOW];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_DW_ANTT];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_EFISCAL];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_EGOVTI];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_FISCALIZACAO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_FORMULARIO_LOP];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_FREQUENCIA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_FREQUENCIA_V2];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_FRETAMENTO_CONTINUO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_GED_DOCFLOW];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_GED_SEI];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_GEO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_GEOFIS];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_GL];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_GL2010];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_HANGFIRE];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_IAF];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_INTEGRACAO_ECARTA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_INTRANET];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_JIRA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_MDFE];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_MERCOSUL];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_MONITRIIP];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_MONITRIIP_MONITORAMENTO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_MONITRIIP_PORTAL];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_MULTAS];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_MULTAS_2];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_NOVO_SCA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_OTM];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_PASSE_LIVRE];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_PEF];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_PGA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_PGD];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_PORTAL_ANTT];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_PORTAL_INTERNET];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_PRODUTO_PERIGOSO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_PROVA_ELETRONICA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_RENAINF];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_RNTRC];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_RNTRC_SEFAZ_WS];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_RNTRC_TAG];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SAFF];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SAFF_TEMPORARIO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SC_ARQ];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SC_CORP];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SC_MSG];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SCA_NG];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SCB];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SCC];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SCD];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SCF];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SEI];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SEMIURBANO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SENDMAIL];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SEP];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SERVICOS];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SGA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SGM];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SGP];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SGRH];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SICAD];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SICAD2];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SICAD3];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SICONPAR];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SICONPAR_PRD];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SIFAMA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SIFAMA_PERFORMANCE];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SIFAT];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SIGEF];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SIGEPRO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SIGICOR];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SIGICOR_BKP_101112];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SIGICOR_TEMP];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SIP];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SIP_BKP];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SIR];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SIREF2];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SISAP];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SISCONTEL];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SISDAP];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SISDAPFROTA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SISDAT];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SISFRET];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SISHAB];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SISHABV2];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SISPASS];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SLA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SLV];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SMD];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SPL];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SPL_V2];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SPL_V2B];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SPP];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SRC];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_STAGE];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_SWF];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_TAXAFIS];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_TESTE_SCRIPT];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_TRIC];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_VALE_PEDAGIO];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_VASTI];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_WSANTT];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_WSP];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [BD_WSRECEITA];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [COMUM];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [MERCOSUL_NOVO_DEV_18092018];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    USE [opencms11];  CREATE LOGIN [antt\noe.evina] FROM WINDOWS WITH DEFAULT_DATABASE=[master];  CREATE USER [antt\noe.evina] FOR LOGIN [antt\noe.evina];  ALTER ROLE [db_datareader] ADD MEMBER [antt\noe.evina];  ALTER ROLE [db_datawriter] ADD MEMBER [antt\noe.evina];  
    