/*DBA: Felipe Lima Portela

select '
USE ['+name+']
DROP USER [antt\noe.evina]
' from sys.databases

felipeportela.com.br

*/


  USE [BD_APOIO]  DROP USER [antt\noe.evina]  
  USE [BD_ASCOM]  DROP USER [antt\noe.evina]  
  USE [BD_AUTORIZACAO]  DROP USER [antt\noe.evina]  
  USE [BD_BARRAMENTO]  DROP USER [antt\noe.evina]  
  USE [BD_BMA]  DROP USER [antt\noe.evina]  
  USE [BD_CANAL_VERDE]  DROP USER [antt\noe.evina]  
  USE [BD_COBRANCA]  DROP USER [antt\noe.evina]  
  USE [BD_COBRANCA_2]  DROP USER [antt\noe.evina]  
  USE [BD_COMUM]  DROP USER [antt\noe.evina]  
  USE [BD_CONTRATO]  DROP USER [antt\noe.evina]  
  USE [BD_CONTROLEACESSO]  DROP USER [antt\noe.evina]  
  USE [BD_CORP]  DROP USER [antt\noe.evina]  
  USE [BD_CORPORATIVO_02]  DROP USER [antt\noe.evina]  
  USE [BD_CORPORATIVO_03]  DROP USER [antt\noe.evina]  
  USE [BD_CORPORATIVO_ANTT]  DROP USER [antt\noe.evina]  
  USE [BD_CPA]  DROP USER [antt\noe.evina]  
  USE [BD_CSS]  DROP USER [antt\noe.evina]  
  USE [BD_DESEMPENHO]  DROP USER [antt\noe.evina]  
  USE [BD_DOCFLOW]  DROP USER [antt\noe.evina]  
  USE [BD_DW_ANTT]  DROP USER [antt\noe.evina]  
  USE [BD_EFISCAL]  DROP USER [antt\noe.evina]  
  USE [BD_EGOVTI]  DROP USER [antt\noe.evina]  
  USE [BD_FISCALIZACAO]  DROP USER [antt\noe.evina]  
  USE [BD_FORMULARIO_LOP]  DROP USER [antt\noe.evina]  
  USE [BD_FREQUENCIA]  DROP USER [antt\noe.evina]  
  USE [BD_FREQUENCIA_V2]  DROP USER [antt\noe.evina]  
  USE [BD_FRETAMENTO_CONTINUO]  DROP USER [antt\noe.evina]  
  USE [BD_GED_DOCFLOW]  DROP USER [antt\noe.evina]  
  USE [BD_GED_SEI]  DROP USER [antt\noe.evina]  
  USE [BD_GEO]  DROP USER [antt\noe.evina]  
  USE [BD_GEOFIS]  DROP USER [antt\noe.evina]  
  USE [BD_GL]  DROP USER [antt\noe.evina]  
  USE [BD_GL2010]  DROP USER [antt\noe.evina]  
  USE [BD_HANGFIRE]  DROP USER [antt\noe.evina]  
  USE [BD_IAF]  DROP USER [antt\noe.evina]  
  USE [BD_INTEGRACAO_ECARTA]  DROP USER [antt\noe.evina]  
  USE [BD_INTRANET]  DROP USER [antt\noe.evina]  
  USE [BD_JIRA]  DROP USER [antt\noe.evina]  
  USE [BD_MDFE]  DROP USER [antt\noe.evina]  
  USE [BD_MERCOSUL]  DROP USER [antt\noe.evina]  
  USE [BD_MONITRIIP]  DROP USER [antt\noe.evina]  
  USE [BD_MONITRIIP_MONITORAMENTO]  DROP USER [antt\noe.evina]  
  USE [BD_MONITRIIP_PORTAL]  DROP USER [antt\noe.evina]  
  USE [BD_MULTAS]  DROP USER [antt\noe.evina]  
  USE [BD_MULTAS_2]  DROP USER [antt\noe.evina]  
  USE [BD_NOVO_SCA]  DROP USER [antt\noe.evina]  
  USE [BD_OTM]  DROP USER [antt\noe.evina]  
  USE [BD_PASSE_LIVRE]  DROP USER [antt\noe.evina]  
  USE [BD_PEF]  DROP USER [antt\noe.evina]  
  USE [BD_PGA]  DROP USER [antt\noe.evina]  
  USE [BD_PGD]  DROP USER [antt\noe.evina]  
  USE [BD_PORTAL_ANTT]  DROP USER [antt\noe.evina]  
  USE [BD_PORTAL_INTERNET]  DROP USER [antt\noe.evina]  
  USE [BD_PRODUTO_PERIGOSO]  DROP USER [antt\noe.evina]  
  USE [BD_PROVA_ELETRONICA]  DROP USER [antt\noe.evina]  
  USE [BD_RENAINF]  DROP USER [antt\noe.evina]  
  USE [BD_RNTRC]  DROP USER [antt\noe.evina]  
  USE [BD_RNTRC_SEFAZ_WS]  DROP USER [antt\noe.evina]  
  USE [BD_RNTRC_TAG]  DROP USER [antt\noe.evina]  
  USE [BD_SAFF]  DROP USER [antt\noe.evina]  
  USE [BD_SAFF_TEMPORARIO]  DROP USER [antt\noe.evina]  
  USE [BD_SC_ARQ]  DROP USER [antt\noe.evina]  
  USE [BD_SC_CORP]  DROP USER [antt\noe.evina]  
  USE [BD_SC_MSG]  DROP USER [antt\noe.evina]  
  USE [BD_SCA_NG]  DROP USER [antt\noe.evina]  
  USE [BD_SCB]  DROP USER [antt\noe.evina]  
  USE [BD_SCC]  DROP USER [antt\noe.evina]  
  USE [BD_SCD]  DROP USER [antt\noe.evina]  
  USE [BD_SCF]  DROP USER [antt\noe.evina]  
  USE [BD_SEI]  DROP USER [antt\noe.evina]  
  USE [BD_SEMIURBANO]  DROP USER [antt\noe.evina]  
  USE [BD_SENDMAIL]  DROP USER [antt\noe.evina]  
  USE [BD_SEP]  DROP USER [antt\noe.evina]  
  USE [BD_SERVICOS]  DROP USER [antt\noe.evina]  
  USE [BD_SGA]  DROP USER [antt\noe.evina]  
  USE [BD_SGM]  DROP USER [antt\noe.evina]  
  USE [BD_SGP]  DROP USER [antt\noe.evina]  
  USE [BD_SGRH]  DROP USER [antt\noe.evina]  
  USE [BD_SICAD]  DROP USER [antt\noe.evina]  
  USE [BD_SICAD2]  DROP USER [antt\noe.evina]  
  USE [BD_SICAD3]  DROP USER [antt\noe.evina]  
  USE [BD_SICONPAR]  DROP USER [antt\noe.evina]  
  USE [BD_SICONPAR_PRD]  DROP USER [antt\noe.evina]  
  USE [BD_SIFAMA]  DROP USER [antt\noe.evina]  
  USE [BD_SIFAMA_PERFORMANCE]  DROP USER [antt\noe.evina]  
  USE [BD_SIFAT]  DROP USER [antt\noe.evina]  
  USE [BD_SIGEF]  DROP USER [antt\noe.evina]  
  USE [BD_SIGEPRO]  DROP USER [antt\noe.evina]  
  USE [BD_SIGICOR]  DROP USER [antt\noe.evina]  
  USE [BD_SIGICOR_BKP_101112]  DROP USER [antt\noe.evina]  
  USE [BD_SIGICOR_TEMP]  DROP USER [antt\noe.evina]  
  USE [BD_SIP]  DROP USER [antt\noe.evina]  
  USE [BD_SIP_BKP]  DROP USER [antt\noe.evina]  
  USE [BD_SIR]  DROP USER [antt\noe.evina]  
  USE [BD_SIREF2]  DROP USER [antt\noe.evina]  
  USE [BD_SISAP]  DROP USER [antt\noe.evina]  
  USE [BD_SISCONTEL]  DROP USER [antt\noe.evina]  
  USE [BD_SISDAP]  DROP USER [antt\noe.evina]  
  USE [BD_SISDAPFROTA]  DROP USER [antt\noe.evina]  
  USE [BD_SISDAT]  DROP USER [antt\noe.evina]  
  USE [BD_SISFRET]  DROP USER [antt\noe.evina]  
  USE [BD_SISHAB]  DROP USER [antt\noe.evina]  
  USE [BD_SISHABV2]  DROP USER [antt\noe.evina]  
  USE [BD_SISPASS]  DROP USER [antt\noe.evina]  
  USE [BD_SLA]  DROP USER [antt\noe.evina]  
  USE [BD_SLV]  DROP USER [antt\noe.evina]  
  USE [BD_SMD]  DROP USER [antt\noe.evina]  
  USE [BD_SPL]  DROP USER [antt\noe.evina]  
  USE [BD_SPL_V2]  DROP USER [antt\noe.evina]  
  USE [BD_SPL_V2B]  DROP USER [antt\noe.evina]  
  USE [BD_SPP]  DROP USER [antt\noe.evina]  
  USE [BD_SRC]  DROP USER [antt\noe.evina]  
  USE [BD_STAGE]  DROP USER [antt\noe.evina]  
  USE [BD_SWF]  DROP USER [antt\noe.evina]  
  USE [BD_TAXAFIS]  DROP USER [antt\noe.evina]  
  USE [BD_TESTE_SCRIPT]  DROP USER [antt\noe.evina]  
  USE [BD_TRIC]  DROP USER [antt\noe.evina]  
  USE [BD_VALE_PEDAGIO]  DROP USER [antt\noe.evina]  
  USE [BD_VASTI]  DROP USER [antt\noe.evina]  
  USE [BD_WSANTT]  DROP USER [antt\noe.evina]  
  USE [BD_WSP]  DROP USER [antt\noe.evina]  
  USE [BD_WSRECEITA]  DROP USER [antt\noe.evina]  
  USE [COMUM]  DROP USER [antt\noe.evina]  
  USE [MERCOSUL_NOVO_DEV_18092018]  DROP USER [antt\noe.evina]  
  USE [opencms11]  DROP USER [antt\noe.evina]  
    
